const CLICK_SEARCH = 'CLICK_SEARCH';
const DATE_CLICKED = 'DATE_CLICKED';
const ADD_DATE = 'ADD_DATE';
const ADD_START = 'ADD_START';
const ADD_END = 'ADD_END';
const RESET_SEARCH = 'RESET_SEARCH';
const SORT_DRIVERS = 'SORT_DRIVERS';
const ADD_DRIVERS = 'ADD_DRIVERS';
const LOADING_DRIVERS = 'LOADING_DRIVERS';

export default {
  CLICK_SEARCH,
  DATE_CLICKED,
  ADD_DATE,
  ADD_START,
  ADD_END,
  RESET_SEARCH,
  SORT_DRIVERS,
  ADD_DRIVERS,
  LOADING_DRIVERS
}