const ADD_USER = 'ADD_USER';
const LOGOUT = 'LOGOUT';
const DELETE_TRIP = 'DELETE_TRIP';
const LOADING_USER = 'LOADING_USER';
const CREATE_USER = 'CREATE_USER';
const CREATING = 'CREATING';

export default {
  LOADING_USER,
  ADD_USER,
  LOGOUT,
  DELETE_TRIP,
  CREATE_USER,
  CREATING
}